# Importing Package

In [0]:
import pandas as pd
import numpy as np

# Reading Data From File

In [2]:
#reading training and testing data along with data which is to be predicted
data=pd.read_csv('train.csv',encoding="latin")
data.columns=['ItemId','Sentiment','SentimentText']
test_data=pd.read_csv('test.csv',encoding="latin")
test_data.columns=['ItemId','SentimentText']

FileNotFoundError: ignored

In [3]:
print(data.shape)
data=data.head(5000)

NameError: ignored

In [0]:
print(test_data.shape)
test_data=test_data.head(5000)

(299989, 2)


In [0]:
#making list of testing data
comments_train=data['SentimentText']
print(comments_train)

0                            is so sad for my APL frie...
1                          I missed the New Moon trail...
2                                 omg its already 7:30 :O
3                 .. Omgaga. Im sooo  im gunna CRy. I'...
4                i think mi bf is cheating on me!!!   ...
5                       or i just worry too much?        
6                      Juuuuuuuuuuuuuuuuussssst Chillin!!
7              Sunny Again        Work Tomorrow  :-|  ...
8             handed in my uniform today . i miss you ...
9                hmmmm.... i wonder how she my number @-)
10                          I must think about positive..
11            thanks to all the haters up in my face a...
12                         this weekend has sucked so far
13                 jb isnt showing in australia any more!
14                                   ok thats it you win.
15          &lt;-------- This is the way i feel right ...
16          awhhe man.... I'm completely useless rt no...
17          Fe

In [0]:
#making list of testing data
comments_test=test_data['SentimentText']
print(comments_test)

0                            is so sad for my APL frie...
1                          I missed the New Moon trail...
2                                 omg its already 7:30 :O
3                 .. Omgaga. Im sooo  im gunna CRy. I'...
4                i think mi bf is cheating on me!!!   ...
5                       or i just worry too much?        
6                      Juuuuuuuuuuuuuuuuussssst Chillin!!
7              Sunny Again        Work Tomorrow  :-|  ...
8             handed in my uniform today . i miss you ...
9                hmmmm.... i wonder how she my number @-)
10                          I must think about positive..
11            thanks to all the haters up in my face a...
12                         this weekend has sucked so far
13                 jb isnt showing in australia any more!
14                                   ok thats it you win.
15          &lt;-------- This is the way i feel right ...
16          awhhe man.... I'm completely useless rt no...
17          Fe

In [0]:
#defining features and traget data
x=data['SentimentText']
y=data['Sentiment']

In [0]:
#splitting train.csv into testing data and testing data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [0]:
y_test.shape

(1000,)

# Processing Text

In [0]:
#converting string in lower case
import string
x_train=[comment.lower() for comment in x_train ]
print(x_train[0:11])

[' my sunglasses are full of ben&amp;jerryâ´s !!', ' sleepy time after men vs wild.&lt;3', ' but i love you, aaron.', " i've lost my clearways.", ' yeps! )) that was amazing! xd finally something away from my house! haha. @myhaloromance', ' i need desprate help! tireddd and now gotta do blooming ict!!', '#dontyouhate stop seeing your crush when classes are over? ', '#3hotwords for now: i am sleepy. good night, people. ', ' i just heard skins music and wants skins back on ', ' i need some different medicine and some food plz. thnx.', ' thinking about school haha']


In [0]:
import nltk
from nltk.tokenize import word_tokenize

In [0]:
#tokenizing each comment in twitter
token=[]
for comment in x_train:
    newtoken=word_tokenize(comment)
    token.append(newtoken)
print(token[0:20000])

[['my', 'sunglasses', 'are', 'full', 'of', 'ben', '&', 'amp', ';', 'jerryâ´s', '!', '!'], ['sleepy', 'time', 'after', 'men', 'vs', 'wild.', '&', 'lt', ';', '3'], ['but', 'i', 'love', 'you', ',', 'aaron', '.'], ['i', "'ve", 'lost', 'my', 'clearways', '.'], ['yeps', '!', ')', ')', 'that', 'was', 'amazing', '!', 'xd', 'finally', 'something', 'away', 'from', 'my', 'house', '!', 'haha', '.', '@', 'myhaloromance'], ['i', 'need', 'desprate', 'help', '!', 'tireddd', 'and', 'now', 'got', 'ta', 'do', 'blooming', 'ict', '!', '!'], ['#', 'dontyouhate', 'stop', 'seeing', 'your', 'crush', 'when', 'classes', 'are', 'over', '?'], ['#', '3hotwords', 'for', 'now', ':', 'i', 'am', 'sleepy', '.', 'good', 'night', ',', 'people', '.'], ['i', 'just', 'heard', 'skins', 'music', 'and', 'wants', 'skins', 'back', 'on'], ['i', 'need', 'some', 'different', 'medicine', 'and', 'some', 'food', 'plz', '.', 'thnx', '.'], ['thinking', 'about', 'school', 'haha'], ['driving', 'to', 'school', 'without', 'justin', 'texting'

In [0]:
table=str.maketrans('','',string.punctuation)
for i in range(len(token)):
    #print(token[i])
    token[i]=[word.translate(table) for word in token[i]]
    token[i]=[word for word in token[i] if word.isalpha()]
print(token[0:11])

[['my', 'sunglasses', 'are', 'full', 'of', 'ben', 'amp'], ['sleepy', 'time', 'after', 'men', 'vs', 'wild', 'lt'], ['but', 'i', 'love', 'you', 'aaron'], ['i', 've', 'lost', 'my', 'clearways'], ['yeps', 'that', 'was', 'amazing', 'xd', 'finally', 'something', 'away', 'from', 'my', 'house', 'haha', 'myhaloromance'], ['i', 'need', 'desprate', 'help', 'tireddd', 'and', 'now', 'got', 'ta', 'do', 'blooming', 'ict'], ['dontyouhate', 'stop', 'seeing', 'your', 'crush', 'when', 'classes', 'are', 'over'], ['for', 'now', 'i', 'am', 'sleepy', 'good', 'night', 'people'], ['i', 'just', 'heard', 'skins', 'music', 'and', 'wants', 'skins', 'back', 'on'], ['i', 'need', 'some', 'different', 'medicine', 'and', 'some', 'food', 'plz', 'thnx'], ['thinking', 'about', 'school', 'haha']]


In [0]:
from nltk.corpus import stopwords
#setting stopwords
stop_words=set(stopwords.words('english'))
#removing stopwords from each comment
for i in range(len(token)):
    token[i]=[w for w in token[i] if not w in stop_words]
print(token[0:11])

[['sunglasses', 'full', 'ben', 'amp'], ['sleepy', 'time', 'men', 'vs', 'wild', 'lt'], ['love', 'aaron'], ['lost', 'clearways'], ['yeps', 'amazing', 'xd', 'finally', 'something', 'away', 'house', 'haha', 'myhaloromance'], ['need', 'desprate', 'help', 'tireddd', 'got', 'ta', 'blooming', 'ict'], ['dontyouhate', 'stop', 'seeing', 'crush', 'classes'], ['sleepy', 'good', 'night', 'people'], ['heard', 'skins', 'music', 'wants', 'skins', 'back'], ['need', 'different', 'medicine', 'food', 'plz', 'thnx'], ['thinking', 'school', 'haha']]


In [0]:
from nltk.stem.porter import PorterStemmer
porter=PorterStemmer()
stems=[]
for i in range(len(token)):
    stems.append([porter.stem(word) for word in token[i]])
print(stems[0])

['sunglass', 'full', 'ben', 'amp']


# Implementing CountVectorizer

In [0]:
#importing required package
from sklearn.feature_extraction.text import CountVectorizer

In [0]:
#building vocab using training data
count_vector=CountVectorizer(tokenizer=lambda doc:doc,lowercase=False)
data_train=count_vector.fit_transform(stems)

In [0]:
data_train=data_train.toarray()

In [0]:
count_vector.get_feature_names()

['aaaaoooowwwww',
 'aaah',
 'aaahh',
 'aah',
 'aahh',
 'aahhh',
 'aaron',
 'aaronxnow',
 'abagail',
 'abbey',
 'abbi',
 'abc',
 'aber',
 'aberdeen',
 'abi',
 'abil',
 'abit',
 'abl',
 'absolut',
 'absolv',
 'abt',
 'abus',
 'ac',
 'accept',
 'accid',
 'accident',
 'accomod',
 'accomplish',
 'accord',
 'account',
 'acct',
 'acdc',
 'acdnt',
 'ach',
 'achaoticbeauti',
 'achey',
 'ack',
 'acl',
 'acoust',
 'across',
 'act',
 'action',
 'activ',
 'actofgreen',
 'actress',
 'actual',
 'ad',
 'adam',
 'adamisacson',
 'adamzz',
 'adbert',
 'add',
 'addict',
 'addictedto',
 'addon',
 'address',
 'addthi',
 'adidasuk',
 'adiict',
 'adjust',
 'admir',
 'admiringli',
 'admit',
 'adopt',
 'adoptapuppi',
 'ador',
 'adorama',
 'adorei',
 'adrianacoffey',
 'adrink',
 'advanc',
 'advantag',
 'adventur',
 'advic',
 'advil',
 'ae',
 'afazenda',
 'afford',
 'afh',
 'afraid',
 'africa',
 'aftermath',
 'afternoon',
 'afuckingmaz',
 'ag',
 'agaaaaain',
 'againcaus',
 'age',
 'agent',
 'aggrav',
 'agil',
 'a

In [0]:
#transforming test data
x=count_vector.transform(x_test)
features=x.toarray()
features.shape

(1000, 6328)

In [0]:
#transforming data for prediction
predicting_features=count_vector.transform(comments_test)


In [0]:
predicting_features=predicting_features.toarray()
predicting_features

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

# classification using scikit learn(SVM) 

In [0]:
from sklearn.svm import SVC
#support vector machine algorithm

In [0]:
classifier = SVC(kernel ='linear')

In [0]:
classifier.fit(data_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [0]:
features.shape

(1000, 6328)

In [0]:
y_pred1= classifier.predict(features)

In [0]:
y_pred1[0]

0

In [0]:
classifier.get_params()

{'C': 1.0,
 'cache_size': 200,
 'class_weight': None,
 'coef0': 0.0,
 'decision_function_shape': 'ovr',
 'degree': 3,
 'gamma': 'auto_deprecated',
 'kernel': 'linear',
 'max_iter': -1,
 'probability': False,
 'random_state': None,
 'shrinking': True,
 'tol': 0.001,
 'verbose': False}

# calculating classification metrics

In [0]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [0]:
print('confusion_matrix:')
print(confusion_matrix(y_test,y_pred1))
print('accuracy_score:', accuracy_score(y_test,y_pred1))
print('Report:')
print(classification_report(y_test,y_pred1))

confusion_matrix:
[[697  21]
 [268  14]]
accuracy_score: 0.711
Report:
              precision    recall  f1-score   support

           0       0.72      0.97      0.83       718
           1       0.40      0.05      0.09       282

   micro avg       0.71      0.71      0.71      1000
   macro avg       0.56      0.51      0.46      1000
weighted avg       0.63      0.71      0.62      1000



In [0]:
import matplotlib.pyplot as plt
from sklearn.model_selection import StratifiedKFold


# Create the validation curve visualizer
cv = StratifiedKFold(12)
param_range = np.logspace(-6, -1, 12)

viz = ValidationCurve(classifier, param_name="gamma", param_range=param_range,
    logx=True, cv=cv, scoring="f1_weighted", n_jobs=8,
)

viz.fit(data_train, y_train)
viz.poof()

# Building Decision Tree Model


In [0]:
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier

In [0]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(data_train,y_train)

#Predict the response for test dataset
y_pred2 = clf.predict(features)


In [0]:
y_pred2[0]

1

# calculating classification metrics


In [0]:
print('confusion_matrix:')
print(confusion_matrix(y_test,y_pred2))
print('accuracy_score:', accuracy_score(y_test,y_pred2))
print('Report:')
print(classification_report(y_test,y_pred2))

confusion_matrix:
[[307 411]
 [103 179]]
accuracy_score: 0.486
Report:
              precision    recall  f1-score   support

           0       0.75      0.43      0.54       718
           1       0.30      0.63      0.41       282

   micro avg       0.49      0.49      0.49      1000
   macro avg       0.53      0.53      0.48      1000
weighted avg       0.62      0.49      0.51      1000



# Import Random Forest Model


In [0]:
from sklearn.ensemble import RandomForestClassifier
#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)
#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(data_train,y_train)
#Predict the response for test dataset
y_pred3=clf.predict(features)

In [0]:
y_pred3[0]

0

# calculating classification metrics

In [0]:
print('confusion_matrix:')
print(confusion_matrix(y_test,y_pred3))
print('accuracy_score:', accuracy_score(y_test,y_pred3))
print('Report:')
print(classification_report(y_test,y_pred3))

confusion_matrix:
[[470 248]
 [175 107]]
accuracy_score: 0.577
Report:
              precision    recall  f1-score   support

           0       0.73      0.65      0.69       718
           1       0.30      0.38      0.34       282

   micro avg       0.58      0.58      0.58      1000
   macro avg       0.52      0.52      0.51      1000
weighted avg       0.61      0.58      0.59      1000



# DEVELOP A BASELINE NEURAL NETWORK MODEL


In [0]:
from keras.models import Sequential
from keras.optimizers import SGD
from keras.layers import Dense

Using TensorFlow backend.


In [0]:
from keras.utils import to_categorical
y1=to_categorical(y_train, num_classes=2, dtype='float32')

In [0]:
y1

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [0]:
y2=to_categorical(y_test, num_classes=2, dtype='float32')

In [0]:
classifier=Sequential()
classifier.add(Dense(10, input_shape=(6328,), init='uniform',use_bias=True))
classifier.add(Dense(2, init='uniform'))

Instructions for updating:
Colocations handled automatically by placer.


C:\Users\HP.HP-PC\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(10, input_shape=(6328,), use_bias=True, kernel_initializer="uniform")`
  
C:\Users\HP.HP-PC\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(2, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until


In [0]:
classifier.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 10)                63290     
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 22        
Total params: 63,312
Trainable params: 63,312
Non-trainable params: 0
_________________________________________________________________


In [0]:
classifier.compile(loss = 'binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [0]:
FITTING=classifier.fit(data_train,y1, validation_data=(features,y2),epochs = 10, batch_size = 2, shuffle = False,verbose=2)

Instructions for updating:
Use tf.cast instead.
Train on 4000 samples, validate on 1000 samples
Epoch 1/10
 - 13s - loss: 1.0323 - acc: 0.5483 - val_loss: 1.7711 - val_acc: 0.5025
Epoch 2/10
 - 8s - loss: 0.6048 - acc: 0.6615 - val_loss: 2.5435 - val_acc: 0.4995
Epoch 3/10
 - 8s - loss: 0.4296 - acc: 0.7434 - val_loss: 3.2963 - val_acc: 0.3640
Epoch 4/10
 - 7s - loss: 0.3016 - acc: 0.7294 - val_loss: 3.7142 - val_acc: 0.2135
Epoch 5/10
 - 7s - loss: 0.2134 - acc: 0.6764 - val_loss: 4.0741 - val_acc: 0.1280
Epoch 6/10
 - 9s - loss: 0.1603 - acc: 0.5793 - val_loss: 4.2684 - val_acc: 0.0895
Epoch 7/10
 - 9s - loss: 0.1276 - acc: 0.4920 - val_loss: 4.3333 - val_acc: 0.0625
Epoch 8/10
 - 8s - loss: 0.1103 - acc: 0.4083 - val_loss: 4.3546 - val_acc: 0.0610
Epoch 9/10
 - 7s - loss: 0.1020 - acc: 0.3676 - val_loss: 4.3763 - val_acc: 0.0600
Epoch 10/10
 - 7s - loss: 0.0961 - acc: 0.3237 - val_loss: 4.3956 - val_acc: 0.0565


In [0]:
y_pred = classifier.predict(features)

In [0]:
features.shape

(1000, 6328)

In [0]:
from sklearn import metrics
y_pred4 = np.zeros_like(y_pred)
y_pred4[np.arange(len(y_pred4)),y_pred.argmax(1)]=1
print(metrics.classification_report(y2,y_pred4))

              precision    recall  f1-score   support

           0       0.72      0.97      0.83       718
           1       0.28      0.02      0.05       282

   micro avg       0.71      0.71      0.71      1000
   macro avg       0.50      0.50      0.44      1000
weighted avg       0.59      0.71      0.61      1000
 samples avg       0.71      0.71      0.71      1000



In [0]:
y_pred4

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

# calculating classification metrics

In [0]:
print('confusion_matrix:')
print(confusion_matrix(y2.argmax(axis=1),y_pred4.argmax(axis=1)))
print('accuracy_score:', accuracy_score(y2,y_pred4))
print('Report:')
print(classification_report(y2,y_pred4))

confusion_matrix:
[[700  18]
 [275   7]]
accuracy_score: 0.707
Report:
              precision    recall  f1-score   support

           0       0.72      0.97      0.83       718
           1       0.28      0.02      0.05       282

   micro avg       0.71      0.71      0.71      1000
   macro avg       0.50      0.50      0.44      1000
weighted avg       0.59      0.71      0.61      1000
 samples avg       0.71      0.71      0.71      1000



In [0]:
import keras
from matplotlib import pyplot as plt
plt.plot(classifier.classifier['acc'])
plt.plot(classifier.classifier['val_acc'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'val'], loc='upper left')
plt.show()

Using TensorFlow backend.


NameError: name 'classifier' is not defined

In [0]:
plt.plot(classifier.classifier['loss'])
plt.plot(classifier.classifier['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'val'], loc='upper left')
plt.show()

# Naive baye's classifier

In [0]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(data_train, y_train)

#Predict the response for test dataset
y_pred5 = gnb.predict(features)

In [0]:
print('confusion_matrix:')
print(confusion_matrix(y_test,y_pred5))
print('accuracy_score:', accuracy_score(y_test,y_pred5))
print('Report:')
print(classification_report(y_test,y_pred5))

confusion_matrix:
[[684  34]
 [271  11]]
accuracy_score: 0.695
Report:
              precision    recall  f1-score   support

           0       0.72      0.95      0.82       718
           1       0.24      0.04      0.07       282

   micro avg       0.69      0.69      0.69      1000
   macro avg       0.48      0.50      0.44      1000
weighted avg       0.58      0.69      0.61      1000



In [0]:
#Import Multinomial Naive Bayes model
from sklearn.naive_bayes import MultinomialNB

#Create a Gaussian Classifier
gnb = MultinomialNB()

#Train the model using the training sets
gnb.fit(data_train, y_train)

#Predict the response for test dataset
y_pred6 = gnb.predict(features)

In [0]:
print('confusion_matrix:')
print(confusion_matrix(y_test,y_pred6))
print('accuracy_score:', accuracy_score(y_test,y_pred6))
print('Report:')
print(classification_report(y_test,y_pred6))

confusion_matrix:
[[654  64]
 [246  36]]
accuracy_score: 0.69
Report:
              precision    recall  f1-score   support

           0       0.73      0.91      0.81       718
           1       0.36      0.13      0.19       282

   micro avg       0.69      0.69      0.69      1000
   macro avg       0.54      0.52      0.50      1000
weighted avg       0.62      0.69      0.63      1000



In [0]:
#Import Bernoulli  Naive Bayes model
from sklearn.naive_bayes import BernoulliNB

#Create a Gaussian Classifier
gnb = BernoulliNB()

#Train the model using the training sets
gnb.fit(data_train, y_train)

#Predict the response for test dataset
y_pred7 = gnb.predict(features)

In [0]:
print('confusion_matrix:')
print(confusion_matrix(y_test,y_pred7))
print('accuracy_score:', accuracy_score(y_test,y_pred7))
print('Report:')
print(classification_report(y_test,y_pred7))

confusion_matrix:
[[580 138]
 [222  60]]
accuracy_score: 0.64
Report:
              precision    recall  f1-score   support

           0       0.72      0.81      0.76       718
           1       0.30      0.21      0.25       282

   micro avg       0.64      0.64      0.64      1000
   macro avg       0.51      0.51      0.51      1000
weighted avg       0.60      0.64      0.62      1000



# TF -IDF Vectorizer

In [0]:
#importing packages
from sklearn.feature_extraction.text import TfidfVectorizer
tf_vector=TfidfVectorizer(tokenizer=lambda doc:doc,lowercase=False)
data_train_tf=tf_vector.fit_transform(stems)

In [0]:
#converting into array
data_train2=data_train_tf.toarray()

In [0]:
test_tf=tf_vector.transform(x_test)
test2=test_tf.toarray()

In [0]:
#transforming data for prediction
actual_features_tf=tf_vector.transform(comments_test)


In [0]:
actual_features_tf=actual_features_tf.toarray()


In [0]:
actual_features_tf

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# classification using scikit learn

In [0]:
from sklearn.svm import SVC
#support vector machine algorithm
classifier = SVC(kernel ='linear')
classifier.fit(data_train2,y_train)
y_pred8 = classifier.predict(test2)

In [0]:
classifier.get_params()

{'C': 1.0,
 'cache_size': 200,
 'class_weight': None,
 'coef0': 0.0,
 'decision_function_shape': 'ovr',
 'degree': 3,
 'gamma': 'auto_deprecated',
 'kernel': 'linear',
 'max_iter': -1,
 'probability': False,
 'random_state': None,
 'shrinking': True,
 'tol': 0.001,
 'verbose': False}

# calculating classification metrics

In [0]:
print('confusion_matrix:')
print(confusion_matrix(y_test,y_pred8))
print('accuracy_score:', accuracy_score(y_test,y_pred8))
print('Report:')
print(classification_report(y_test,y_pred8))

confusion_matrix:
[[710   8]
 [276   6]]
accuracy_score: 0.716
Report:
              precision    recall  f1-score   support

           0       0.72      0.99      0.83       718
           1       0.43      0.02      0.04       282

   micro avg       0.72      0.72      0.72      1000
   macro avg       0.57      0.51      0.44      1000
weighted avg       0.64      0.72      0.61      1000



# Building Decision Tree Model

In [0]:
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier

In [0]:
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(data_train2,y_train)

#Predict the response for test dataset
y_pred9 = clf.predict(test2)

# calculating classification metrics


In [0]:
print('confusion_matrix:')
print(confusion_matrix(y_test,y_pred9))
print('accuracy_score:', accuracy_score(y_test,y_pred9))
print('Report:')
print(classification_report(y_test,y_pred9))

confusion_matrix:
[[391 327]
 [143 139]]
accuracy_score: 0.53
Report:
              precision    recall  f1-score   support

           0       0.73      0.54      0.62       718
           1       0.30      0.49      0.37       282

   micro avg       0.53      0.53      0.53      1000
   macro avg       0.52      0.52      0.50      1000
weighted avg       0.61      0.53      0.55      1000



# Import Random Forest Model


In [0]:
from sklearn.ensemble import RandomForestClassifier
#Create a Gaussian Classifier
clf=RandomForestClassifier(n_estimators=100)
#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(data_train2,y_train)
#Predict the response for test dataset
y_pred10 =clf.predict(test2)

# calculating classification metrics


In [0]:
print('confusion_matrix:')
print(confusion_matrix(y_test,y_pred10))
print('accuracy_score:', accuracy_score(y_test,y_pred10))
print('Report:')
print(classification_report(y_test,y_pred10))

confusion_matrix:
[[642  76]
 [239  43]]
accuracy_score: 0.685
Report:
              precision    recall  f1-score   support

           0       0.73      0.89      0.80       718
           1       0.36      0.15      0.21       282

   micro avg       0.69      0.69      0.69      1000
   macro avg       0.55      0.52      0.51      1000
weighted avg       0.63      0.69      0.64      1000



# DEVELOP A BASELINE NEURAL NETWORK MODEL


In [0]:
from keras.models import Sequential
from keras.optimizers import SGD
from keras.layers import Dense

In [0]:
from keras.utils import to_categorical
y1=to_categorical(y_train, num_classes=2, dtype='float32')
y2=to_categorical(y_test, num_classes=2, dtype='float32')

In [0]:
classifier=Sequential()
classifier.add(Dense(10, input_shape=(6328,), init='uniform',use_bias=True))
classifier.add(Dense(2, init='uniform'))
classifier.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 10)                63290     
_________________________________________________________________
dense_6 (Dense)              (None, 2)                 22        
Total params: 63,312
Trainable params: 63,312
Non-trainable params: 0
_________________________________________________________________


C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(10, input_shape=(6328,), use_bias=True, kernel_initializer="uniform")`
  
C:\Users\HP\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(2, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until


In [0]:
classifier.compile(loss = 'binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [0]:
FITTING=classifier.fit(data_train2,y1, validation_data=(test2,y2),epochs = 10, batch_size = 2, shuffle = False,verbose=2)

Train on 4000 samples, validate on 1000 samples
Epoch 1/10
 - 8s - loss: 0.7572 - acc: 0.6551 - val_loss: 0.6168 - val_acc: 0.7065
Epoch 2/10
 - 7s - loss: 0.4735 - acc: 0.7685 - val_loss: 0.6167 - val_acc: 0.6880
Epoch 3/10
 - 7s - loss: 0.3048 - acc: 0.8491 - val_loss: 1.1177 - val_acc: 0.6935
Epoch 4/10
 - 7s - loss: 0.2251 - acc: 0.8104 - val_loss: 2.4757 - val_acc: 0.6855
Epoch 5/10
 - 7s - loss: 0.1721 - acc: 0.7556 - val_loss: 3.2613 - val_acc: 0.6330
Epoch 6/10
 - 7s - loss: 0.1407 - acc: 0.6786 - val_loss: 3.7658 - val_acc: 0.4415
Epoch 7/10
 - 7s - loss: 0.1214 - acc: 0.5958 - val_loss: 3.8729 - val_acc: 0.3200
Epoch 8/10
 - 7s - loss: 0.1189 - acc: 0.5004 - val_loss: 3.9945 - val_acc: 0.2625
Epoch 9/10
 - 7s - loss: 0.0997 - acc: 0.4723 - val_loss: 3.9523 - val_acc: 0.2815
Epoch 10/10
 - 7s - loss: 0.0911 - acc: 0.4597 - val_loss: 4.0714 - val_acc: 0.2180


In [0]:
y_pred = classifier.predict(features)

# calculating classification metrics


In [0]:
from sklearn import metrics
y_pred11 = np.zeros_like(y_pred)
y_pred11[np.arange(len(y_pred11)),y_pred11.argmax(1)]=1
#print(metrics.classification_report(y2,y_pred1))


In [0]:
print('confusion_matrix:')
print(confusion_matrix(y2.argmax(axis=1),y_pred.argmax(axis=1)))
print('accuracy_score:', accuracy_score(y2,y_pred11))
print('Report:')
print(classification_report(y2,y_pred11))

confusion_matrix:
[[667  51]
 [260  22]]
accuracy_score: 0.718
Report:
              precision    recall  f1-score   support

           0       0.72      1.00      0.84       718
           1       0.00      0.00      0.00       282

   micro avg       0.72      0.72      0.72      1000
   macro avg       0.36      0.50      0.42      1000
weighted avg       0.52      0.72      0.60      1000
 samples avg       0.72      0.72      0.72      1000



C:\Users\HP\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


# Naive baye's classifier


In [0]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(data_train2, y_train)

#Predict the response for test dataset
y_pred12 = gnb.predict(test2)

In [0]:
print('confusion_matrix:')
print(confusion_matrix(y_test,y_pred12))
print('accuracy_score:', accuracy_score(y_test,y_pred12))
print('Report:')
print(classification_report(y_test,y_pred12))

confusion_matrix:
[[684  34]
 [271  11]]
accuracy_score: 0.695
Report:
              precision    recall  f1-score   support

           0       0.72      0.95      0.82       718
           1       0.24      0.04      0.07       282

   micro avg       0.69      0.69      0.69      1000
   macro avg       0.48      0.50      0.44      1000
weighted avg       0.58      0.69      0.61      1000



In [0]:
#Import Multinomial Naive Bayes model
from sklearn.naive_bayes import MultinomialNB

#Create a Gaussian Classifier
gnb = MultinomialNB()

#Train the model using the training sets
gnb.fit(data_train2, y_train)

#Predict the response for test dataset
y_pred13 = gnb.predict(test2)

In [0]:
print('confusion_matrix:')
print(confusion_matrix(y_test,y_pred13))
print('accuracy_score:', accuracy_score(y_test,y_pred13))
print('Report:')
print(classification_report(y_test,y_pred13))

confusion_matrix:
[[718   0]
 [282   0]]
accuracy_score: 0.718
Report:
              precision    recall  f1-score   support

           0       0.72      1.00      0.84       718
           1       0.00      0.00      0.00       282

   micro avg       0.72      0.72      0.72      1000
   macro avg       0.36      0.50      0.42      1000
weighted avg       0.52      0.72      0.60      1000



C:\Users\HP\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [0]:
#Import Bernoulli  Naive Bayes model
from sklearn.naive_bayes import BernoulliNB

#Create a Gaussian Classifier
gnb = BernoulliNB()

#Train the model using the training sets
gnb.fit(data_train2, y_train)

#Predict the response for test dataset
y_pred14 = gnb.predict(test2)

In [0]:
print('confusion_matrix:')
print(confusion_matrix(y_test,y_pred14))
print('accuracy_score:', accuracy_score(y_test,y_pred14))
print('Report:')
print(classification_report(y_test,y_pred14))

confusion_matrix:
[[580 138]
 [222  60]]
accuracy_score: 0.64
Report:
              precision    recall  f1-score   support

           0       0.72      0.81      0.76       718
           1       0.30      0.21      0.25       282

   micro avg       0.64      0.64      0.64      1000
   macro avg       0.51      0.51      0.51      1000
weighted avg       0.60      0.64      0.62      1000

